//------------------------------------------------------------------------------
// <auto-generated>
//	 Este código fue generado por una herramienta.
//	 Versión de runtime:4.0.30319.34003
//
//	 Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//	 se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vCard_Editor.Properties {
	using System;
	
	
	/// <summary>
	///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
	/// </summary>
	// StronglyTypedResourceBuilder generó automáticamente esta clase
	// a través de una herramienta como ResGen o Visual Studio.
	// Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
	// con la opción /str o recompile su proyecto de VS.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class Resources {
		
		static global::System.Resources.ResourceManager resourceMan;
		
		static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Resources() {
		}
		
		/// <summary>
		///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("vCard_Editor.Properties.Resources", typeof(Resources).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
		///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a {\rtf1\ansi\ansicpg1252\deff0\nouicompat{\fonttbl{\f0\fnil\fcharset0 Calibri;}{\f1\fnil\fcharset2 Symbol;}}
		///{\colortbl ;\red0\green0\blue255;}
		///{\*\generator Riched20 6.3.9600}\viewkind4\uc1 
		///\pard\sa200\sl276\slmult1\ul\b\f0\fs56\lang10 Ayuda\par
		///\ulnone\b0\fs24 Si tienes alguna duda sobre el funcionamiento de vCard Editor, puedes leer la ayuda de la que dispones a continuaci\&apos;f3n para esclarecerla.\fs22\par
		///\b\fs40 Introducci\&apos;f3n\b0\fs24\par
		///vCard Editor es un programa dise\&apos;f1ado por Lonami ({{\fie [resto de la cadena truncado]&quot;;.
		/// </summary>
		internal static string help {
			get {
				return ResourceManager.GetString("help", resourceCulture);
			}
		}
	}
}
